Add /snowflake command
DJDavid98/HammerTimeBot pull request #32
Opened 2023-03-17 14:10 UTC by Jessuhh

This command allows you to generate timestamps by giving it a snowflake id. Below is a gif of how it works:
![DiscordSnowflakeCommand](https://user-images.githubusercontent.com/58728143/225925421-7f21d663-eb75-46ed-a6ed-9d6ed37a6b37.gif)
(this pr does **not** include context menu commands)

Because discord snowflakes exceed the max limit of the `ApplicationCommandOptionType.Number` I had to resort to a string input. As you can see in the gif above, invalid snowflakes will be dealed with properly.

I have no idea if I implemented this properly. I tried to keep to the current structure as much as possible. I'm mainly worried about the translations not being done correctly, since I just added them to `src/locales/en-US/translation.json`. Feel free to change anything you don't like. Any feedback is welcome!

2023-03-17 14:11 UTC, Jessuhh commented
Implements #31

2023-03-17 14:19 UTC, DJDavid98 commented on package.json
> +  "description": "Discord bot version of https://hammertime.cyou using slash commands",
Ooops, nice catch xD

2023-03-17 14:38 UTC, DJDavid98 requested changes

2023-03-17 14:38 UTC, DJDavid98 commented on src/commands/snowflake.command.ts
> +function snowflakeToUnix(snowflake: string) {
This function should be extracted to the `utils` folder, preferably with some unit tests. Command files are only really supposed to contain the command definitions

2023-03-17 14:38 UTC, DJDavid98 commented on src/locales/en-US/translation.json
> +      "description": "Display the syntaxes for a specific Discord snowflake",
I would prefer to word this as
```suggestion
      "description": "Display the syntax for the timestamp of a Snowflake (most IDs within Discord)",
```

2023-03-17 14:38 UTC, DJDavid98 commented on src/locales/en-US/translation.json
> +          "description": "The Discord snowflake"
I would avoid duplicating Discord here, besides redundancy the less mentions of it are in the code the more comfortable I feel about how clear it is that the bot is not affiliated with anything official
```suggestion
          "description": "The Snowflake number"
```

2023-03-17 14:38 UTC, DJDavid98 commented on src/types/bot-interaction.ts
> +  SNOWFLAKE = 'snowflake'
This enum is meant to be alphabetically sorted, please insert this new value after `IN`

2023-03-20 17:32 UTC, DJDavid98 approved these changes

2023-03-20 17:34 UTC, merged

2026-10-01 06:23 UTC, ghsjdrmcwj-png commented on package.json
> +  "description": "Discord bot version of https://hammertime.cyou using slash commands",
через 11 часов